# Copyright (C) 2024, twiinIT
# SPDX-License-Identifier: BSD-3-Clause

from cosapp.systems import System

class TurbopropAero(System):
    """Turboprop model aero performances computation.

    Inputs
    ------

    Outputs
    -------
    """

    def setup(self):
        # inwards
        self.add_inward(
            "primary_nozzle_thrust", 0.0, unit="N", desc="total thrust generated by primary nozzle"
        )
        self.add_inward(
            "propeller_thrust", 0.0, unit="N", desc="total thrust generated by propeller"
        )

        self.add_inward("fuel_W", 1.0, unit="kg/s", desc="fuel mass flow")

        # outwards
        self.add_outward("thrust", 1.0, unit="N", desc="engine thrust")
        self.add_outward("sfc", 1.0, unit="kg / (daN * h)", desc="specific consumption")
        self.add_outward("opr", 1.0, unit="", desc="overall pressure ratio")

    def compute(self):
        self.thrust = self.primary_nozzle_thrust + self.propeller_thrust
        self.sfc = self.fuel_W * 3600 / (self.thrust / 10)
